package org.recompile.mobile;
import java.io.*;
import javax.microedition.midlet.MIDlet;
import javax.microedition.lcdui.*;
public final class M114R5BProportionalDiagnosticMIDlet extends MIDlet implements Runnable {
 private Canvas canvas; private boolean captured;
 protected void startApp(){
  final Font sys=Font.getFont(Font.FACE_SYSTEM,Font.STYLE_PLAIN,Font.SIZE_MEDIUM);
  final Font prop=Font.getFont(Font.FACE_PROPORTIONAL,Font.STYLE_PLAIN,Font.SIZE_MEDIUM);
  System.out.println("M1_14_R5B_PRIMARY_VARIABLE=PROPORTIONAL_DIAGNOSTIC_ONLY");
  System.out.println("M1_14_R5B_RENDERER_CHANGE=NONE"); log("SYSTEM",sys); log("PROPORTIONAL",prop);
  canvas=new Canvas(){protected void paint(Graphics g){g.setColor(0x17324A);g.fillRect(0,0,getWidth(),getHeight());g.setColor(0xFFFFFF);g.setFont(sys);g.drawString("SYSTEM: iii WWW Il1 mw @.,",24,72,Graphics.TOP|Graphics.LEFT);g.drawString("SYSTEM: Ti\u1EBFng Vi\u1EC7t - \u4E2D\u6587",24,104,Graphics.TOP|Graphics.LEFT);g.setFont(prop);g.drawString("PROP: iii WWW Il1 mw @.,",24,168,Graphics.TOP|Graphics.LEFT);g.drawString("PROP: Ti\u1EBFng Vi\u1EC7t - \u4E2D\u6587",24,200,Graphics.TOP|Graphics.LEFT);g.setFont(sys);g.drawString("r5B diagnostic: no renderer change",24,288,Graphics.TOP|Graphics.LEFT);}};
  canvas.setFullScreenMode(true);Display.getDisplay(this).setCurrent(canvas);System.out.println("M1_14_R5B_CANVAS_VISIBLE_READY=YES");new Thread(this,"m114-r5b-presenter").start();
 }
 private static void log(String n,Font f){String[] s={"ABC 123","iii","WWW","Il1","mw","@.,","Ti\u1EBFng Vi\u1EC7t","\u4E2D\u6587"};String[] k={"ASCII","III","WWW","IL1","MW","PUNCT","VN","CJK"};System.out.println("M1_14_R5B_"+n+"_FACE="+f.getFace());System.out.println("M1_14_R5B_"+n+"_HEIGHT="+f.getHeight());System.out.println("M1_14_R5B_"+n+"_BASELINE="+f.getBaselinePosition());for(int i=0;i<s.length;i++)System.out.println("M1_14_R5B_"+n+"_"+k[i]+"_WIDTH="+f.stringWidth(s[i]));for(int c=32;c<=126;c++){char ch=(char)c;System.out.println("M1_14_R5B_"+n+"_CHAR_"+c+"="+f.charWidth(ch));}}
 private static void le16(FileOutputStream o,int v)throws Exception{o.write(v&255);o.write((v>>>8)&255);}private static void le32(FileOutputStream o,int v)throws Exception{o.write(v&255);o.write((v>>>8)&255);o.write((v>>>16)&255);o.write((v>>>24)&255);}
 private void bmp(int[] p,int w,int h,String path)throws Exception{int row=((w*3+3)/4)*4,img=row*h;FileOutputStream o=new FileOutputStream(path);o.write('B');o.write('M');le32(o,54+img);le16(o,0);le16(o,0);le32(o,54);le32(o,40);le32(o,w);le32(o,h);le16(o,1);le16(o,24);le32(o,0);le32(o,img);le32(o,2835);le32(o,2835);le32(o,0);le32(o,0);for(int y=h-1;y>=0;y--){for(int x=0;x<w;x++){int v=p[y*w+x];o.write(v&255);o.write((v>>>8)&255);o.write((v>>>16)&255);}for(int q=w*3;q<row;q++)o.write(0);}o.close();}
 private void capture(int[] p,int w,int h,int frame){if(captured||p==null||p.length<w*h)return;captured=true;try{String shot="/mnt/mmc/RG35XX-MIYOO-M1.14-R5B-SCREENSHOT.bmp",meta="/mnt/mmc/RG35XX-MIYOO-M1.14-R5B-LIVE-FRAME.txt";bmp(p,w,h,shot);PrintStream m=new PrintStream(new FileOutputStream(meta));m.println("M1_14_R5B_LIVE_CAPTURE=PASS");m.println("M1_14_R5B_CAPTURE_METHOD=JAVA_ARGB_BEFORE_PRESENTER");m.println("M1_14_R5B_SCREENSHOT=PASS");m.println("M1_14_R5B_FRAME="+frame);m.println("M1_14_R5B_WIDTH="+w);m.println("M1_14_R5B_HEIGHT="+h);m.close();System.out.println("M1_14_R5B_LIVE_CAPTURE=PASS FRAME="+frame);System.out.println("M1_14_R5B_SCREENSHOT=PASS PATH="+shot);}catch(Throwable t){System.out.println("M1_14_R5B_CAPTURE=FAIL "+t);}}
 public void run(){int rc=M19SdlPresenter.initDisplay();System.out.println("M1_14_R5B_NATIVE_INIT_RC="+rc);if(rc!=0)System.exit(1);long end=System.currentTimeMillis()+12000L;int n=0;while(System.currentTimeMillis()<end){canvas.repaint();canvas.serviceRepaints();PlatformImage im=MobilePlatform.getLcdBackbuffer();if(im!=null){int[] f=im.getMIDPGraphics().getFrameBuffer();if(!captured&&n>=20)capture(f,640,480,n);if(M19SdlPresenter.presentARGB(f,640,480)!=0)break;n++;}try{Thread.sleep(50);}catch(Exception e){break;}}M19SdlPresenter.shutdownDisplay();System.out.println("M1_14_R5B_PRESENT_COUNT="+n);System.out.println("M1_14_R5B_NORMAL_EXIT=PASS");System.exit(n>0&&captured?0:2);}protected void pauseApp(){}protected void destroyApp(boolean u){}
}
