package org.recompile.mobile;
import java.io.*;
import javax.microedition.midlet.MIDlet;
import javax.microedition.lcdui.*;
public final class M114R5AMonospaceSemanticsMIDlet extends MIDlet implements Runnable {
 private Canvas canvas; private boolean captured;
 protected void startApp(){
  final Font system=Font.getFont(Font.FACE_SYSTEM,Font.STYLE_PLAIN,Font.SIZE_MEDIUM);
  final Font mono=Font.getFont(Font.FACE_MONOSPACE,Font.STYLE_PLAIN,Font.SIZE_MEDIUM);
  System.out.println("M1_14_R5A_PRIMARY_VARIABLE=MONOSPACE_LAYOUT_SEMANTICS_ONLY");
  log("SYSTEM",system); log("MONOSPACE",mono);
  canvas=new Canvas(){protected void paint(Graphics g){g.setColor(0x123050);g.fillRect(0,0,getWidth(),getHeight());g.setColor(0xFFFFFF);g.setFont(system);g.drawString("SYSTEM: ABC 123 - iii - WWW",24,80,Graphics.TOP|Graphics.LEFT);g.drawString("SYSTEM: Ti\u1EBFng Vi\u1EC7t - \u4E2D\u6587",24,112,Graphics.TOP|Graphics.LEFT);g.setFont(mono);g.drawString("MONO: ABC 123 - iii - WWW",24,176,Graphics.TOP|Graphics.LEFT);g.drawString("MONO: Ti\u1EBFng Vi\u1EC7t - \u4E2D\u6587",24,208,Graphics.TOP|Graphics.LEFT);g.setFont(system);g.drawString("r5A: MONOSPACE fixed 12-cell A/B",24,288,Graphics.TOP|Graphics.LEFT);}};
  canvas.setFullScreenMode(true);Display.getDisplay(this).setCurrent(canvas);System.out.println("M1_14_R5A_CANVAS_VISIBLE_READY=YES");new Thread(this,"m114-r5a-presenter").start();
 }
 private static void log(String n,Font f){System.out.println("M1_14_R5A_"+n+"_FACE="+f.getFace());System.out.println("M1_14_R5A_"+n+"_STYLE="+f.getStyle());System.out.println("M1_14_R5A_"+n+"_SIZE="+f.getSize());System.out.println("M1_14_R5A_"+n+"_HEIGHT="+f.getHeight());System.out.println("M1_14_R5A_"+n+"_BASELINE="+f.getBaselinePosition());System.out.println("M1_14_R5A_"+n+"_ASCII_WIDTH="+f.stringWidth("ABC 123"));System.out.println("M1_14_R5A_"+n+"_III_WIDTH="+f.stringWidth("iii"));System.out.println("M1_14_R5A_"+n+"_WWW_WIDTH="+f.stringWidth("WWW"));System.out.println("M1_14_R5A_"+n+"_VN_WIDTH="+f.stringWidth("Ti\u1EBFng Vi\u1EC7t"));System.out.println("M1_14_R5A_"+n+"_CJK_WIDTH="+f.stringWidth("\u4E2D\u6587"));}
 private static void le16(FileOutputStream o,int v)throws Exception{o.write(v&255);o.write((v>>>8)&255);}private static void le32(FileOutputStream o,int v)throws Exception{o.write(v&255);o.write((v>>>8)&255);o.write((v>>>16)&255);o.write((v>>>24)&255);}
 private void bmp(int[] p,int w,int h,String path)throws Exception{int row=((w*3+3)/4)*4,img=row*h;FileOutputStream o=new FileOutputStream(path);o.write('B');o.write('M');le32(o,54+img);le16(o,0);le16(o,0);le32(o,54);le32(o,40);le32(o,w);le32(o,h);le16(o,1);le16(o,24);le32(o,0);le32(o,img);le32(o,2835);le32(o,2835);le32(o,0);le32(o,0);for(int y=h-1;y>=0;y--){for(int x=0;x<w;x++){int v=p[y*w+x];o.write(v&255);o.write((v>>>8)&255);o.write((v>>>16)&255);}for(int q=w*3;q<row;q++)o.write(0);}o.close();}
 private void capture(int[] p,int w,int h,int frame){if(captured||p==null||p.length<w*h)return;captured=true;try{String shot="/mnt/mmc/RG35XX-MIYOO-M1.14-R5A-SCREENSHOT.bmp",meta="/mnt/mmc/RG35XX-MIYOO-M1.14-R5A-LIVE-FRAME.txt";bmp(p,w,h,shot);PrintStream m=new PrintStream(new FileOutputStream(meta));m.println("M1_14_R5A_LIVE_CAPTURE=PASS");m.println("M1_14_R5A_CAPTURE_METHOD=JAVA_ARGB_BEFORE_PRESENTER");m.println("M1_14_R5A_SCREENSHOT=PASS");m.println("M1_14_R5A_SCREENSHOT_PATH="+shot);m.println("M1_14_R5A_FRAME="+frame);m.println("M1_14_R5A_WIDTH="+w);m.println("M1_14_R5A_HEIGHT="+h);m.close();System.out.println("M1_14_R5A_LIVE_CAPTURE=PASS FRAME="+frame);System.out.println("M1_14_R5A_SCREENSHOT=PASS PATH="+shot);}catch(Throwable t){System.out.println("M1_14_R5A_CAPTURE=FAIL "+t);}}
 public void run(){int rc=M19SdlPresenter.initDisplay();System.out.println("M1_14_R5A_NATIVE_INIT_RC="+rc);if(rc!=0)System.exit(1);long end=System.currentTimeMillis()+12000L;int n=0;while(System.currentTimeMillis()<end){canvas.repaint();canvas.serviceRepaints();PlatformImage im=MobilePlatform.getLcdBackbuffer();if(im!=null){int[] f=im.getMIDPGraphics().getFrameBuffer();if(!captured&&n>=20)capture(f,640,480,n);if(M19SdlPresenter.presentARGB(f,640,480)!=0)break;n++;}try{Thread.sleep(50);}catch(Exception e){break;}}M19SdlPresenter.shutdownDisplay();System.out.println("M1_14_R5A_PRESENT_COUNT="+n);System.out.println("M1_14_R5A_NORMAL_EXIT=PASS");System.exit(n>0&&captured?0:2);}protected void pauseApp(){}protected void destroyApp(boolean u){}
}
