package org.recompile.mobile;
import java.io.*;
import javax.microedition.midlet.MIDlet;
import javax.microedition.lcdui.*;
public final class M114R6FontMatrixRegressionMIDlet extends MIDlet implements Runnable {
 private Canvas canvas; private boolean captured;
 private static final int[] FACES={Font.FACE_SYSTEM,Font.FACE_MONOSPACE,Font.FACE_PROPORTIONAL};
 private static final String[] FN={"SYSTEM","MONO","PROP"};
 private static final int[] STYLES={Font.STYLE_PLAIN,Font.STYLE_BOLD,Font.STYLE_ITALIC,Font.STYLE_UNDERLINED};
 private static final String[] SN={"PLAIN","BOLD","ITALIC","UNDER"};
 private static final int[] SIZES={Font.SIZE_SMALL,Font.SIZE_MEDIUM,Font.SIZE_LARGE};
 private static final String[] ZN={"SMALL","MEDIUM","LARGE"};
 protected void startApp(){System.out.println("M1_14_R6_PRIMARY_VARIABLE=NONE_REGRESSION_ONLY");System.out.println("M1_14_R6_MATRIX_EXPECTED=36");int n=0;for(int f=0;f<3;f++)for(int s=0;s<4;s++)for(int z=0;z<3;z++){Font x=Font.getFont(FACES[f],STYLES[s],SIZES[z]);String p="M1_14_R6_"+FN[f]+"_"+SN[s]+"_"+ZN[z];System.out.println(p+"_FACE="+x.getFace());System.out.println(p+"_STYLE="+x.getStyle());System.out.println(p+"_SIZE="+x.getSize());System.out.println(p+"_HEIGHT="+x.getHeight());System.out.println(p+"_BASELINE="+x.getBaselinePosition());System.out.println(p+"_ASCII="+x.stringWidth("ABC 123"));System.out.println(p+"_III="+x.stringWidth("iii"));System.out.println(p+"_WWW="+x.stringWidth("WWW"));System.out.println(p+"_VN="+x.stringWidth("Ti\u1EBFng Vi\u1EC7t"));System.out.println(p+"_CJK="+x.stringWidth("\u4E2D\u6587"));n++;}System.out.println("M1_14_R6_MATRIX_COUNT="+n);canvas=new Canvas(){protected void paint(Graphics g){g.setColor(0x17324A);g.fillRect(0,0,getWidth(),getHeight());g.setColor(0xFFFFFF);int y=18;for(int f=0;f<3;f++){for(int s=0;s<4;s++){Font x=Font.getFont(FACES[f],STYLES[s],Font.SIZE_MEDIUM);g.setFont(x);g.drawString(FN[f]+" "+SN[s]+": iii WWW Ti\u1EBFng Vi\u1EC7t \u4E2D\u6587",14,y,Graphics.TOP|Graphics.LEFT);y+=25;}y+=8;}g.setFont(Font.getFont(Font.FACE_PROPORTIONAL,Font.STYLE_BOLD|Font.STYLE_ITALIC|Font.STYLE_UNDERLINED,Font.SIZE_LARGE));g.drawString("PROP COMBO LARGE: Vi\u1EC7t \u4E2D\u6587",14,y,Graphics.TOP|Graphics.LEFT);}};canvas.setFullScreenMode(true);Display.getDisplay(this).setCurrent(canvas);System.out.println("M1_14_R6_CANVAS_VISIBLE_READY=YES");new Thread(this,"m114-r6-presenter").start();}
 private static void le16(FileOutputStream o,int v)throws Exception{o.write(v&255);o.write((v>>>8)&255);}private static void le32(FileOutputStream o,int v)throws Exception{o.write(v&255);o.write((v>>>8)&255);o.write((v>>>16)&255);o.write((v>>>24)&255);}
 private void bmp(int[] p,int w,int h,String path)throws Exception{int row=((w*3+3)/4)*4,img=row*h;FileOutputStream o=new FileOutputStream(path);o.write('B');o.write('M');le32(o,54+img);le16(o,0);le16(o,0);le32(o,54);le32(o,40);le32(o,w);le32(o,h);le16(o,1);le16(o,24);le32(o,0);le32(o,img);le32(o,2835);le32(o,2835);le32(o,0);le32(o,0);for(int y=h-1;y>=0;y--){for(int x=0;x<w;x++){int v=p[y*w+x];o.write(v&255);o.write((v>>>8)&255);o.write((v>>>16)&255);}for(int q=w*3;q<row;q++)o.write(0);}o.close();}
 private void capture(int[] p,int w,int h,int frame){if(captured||p==null||p.length<w*h)return;captured=true;try{String shot="/mnt/mmc/RG35XX-MIYOO-M1.14-R6-SCREENSHOT.bmp",meta="/mnt/mmc/RG35XX-MIYOO-M1.14-R6-LIVE-FRAME.txt";bmp(p,w,h,shot);PrintStream m=new PrintStream(new FileOutputStream(meta));m.println("M1_14_R6_LIVE_CAPTURE=PASS");m.println("M1_14_R6_CAPTURE_METHOD=JAVA_ARGB_BEFORE_PRESENTER");m.println("M1_14_R6_SCREENSHOT=PASS");m.println("M1_14_R6_FRAME="+frame);m.println("M1_14_R6_WIDTH="+w);m.println("M1_14_R6_HEIGHT="+h);m.close();System.out.println("M1_14_R6_LIVE_CAPTURE=PASS FRAME="+frame);System.out.println("M1_14_R6_SCREENSHOT=PASS PATH="+shot);}catch(Throwable t){System.out.println("M1_14_R6_CAPTURE=FAIL "+t);}}
 public void run(){int rc=M19SdlPresenter.initDisplay();System.out.println("M1_14_R6_NATIVE_INIT_RC="+rc);if(rc!=0)System.exit(1);long end=System.currentTimeMillis()+12000L;int n=0;while(System.currentTimeMillis()<end){canvas.repaint();canvas.serviceRepaints();PlatformImage im=MobilePlatform.getLcdBackbuffer();if(im!=null){int[] f=im.getMIDPGraphics().getFrameBuffer();if(!captured&&n>=20)capture(f,640,480,n);if(M19SdlPresenter.presentARGB(f,640,480)!=0)break;n++;}try{Thread.sleep(50);}catch(Exception e){break;}}M19SdlPresenter.shutdownDisplay();System.out.println("M1_14_R6_PRESENT_COUNT="+n);System.out.println("M1_14_R6_NORMAL_EXIT=PASS");System.exit(n>0&&captured?0:2);}protected void pauseApp(){}protected void destroyApp(boolean u){}
}
