#!/bin/sh
set -u

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" 2>/dev/null && pwd)
JAMVM=${P2B_JAMVM:-/mnt/mmc/CFW/java/bin/jamvm}
GLIBJ=${P2B_GLIBJ:-/mnt/mmc/CFW/java/share/classpath/glibj.zip}
JAR="$ROOT/P2B-PROTECTED-JAMVM-PLANNER-PROBE.jar"
REF="$ROOT/P2B-PLANNER-REFERENCE.tsv"
MANIFEST="$ROOT/PROBE-SHA256SUMS.txt"
OUT=${P2B_RESULT:-/mnt/mmc/P2B-PROTECTED-JAMVM-PLANNER-RESULT.txt}

EXPECTED_JAMVM=eea1b97cebfaca67b69ed365e966d80cdac22d8ff245c7a556137cfb2898ea34
EXPECTED_GLIBJ=d7abe888d2980329434c30f18c0eec124be1f02284bf9ed28e88d7242a1f2bea

: >"$OUT" || exit 30
echo 'PROJECT=RG35XX-AWEIGIT-R1' >>"$OUT"
echo 'STAGE=P2B-PROTECTED-JAMVM-PLANNER-COMPATIBILITY' >>"$OUT"
echo 'SCOPE=FONT_TEXT_PLANNER_MODULE_ONLY' >>"$OUT"
echo 'RUNTIME_DELTA=NONE' >>"$OUT"
echo 'RUNTIME_PATCH=FORBIDDEN' >>"$OUT"
echo 'RUNTIME_CANDIDATE_BRANCH=DO_NOT_CREATE' >>"$OUT"
echo 'PLATFORM_DEVICE_PASS=NOT_TESTED' >>"$OUT"

fail() {
  echo "P2B_PROBE_PRECONDITION=FAIL:$1" >>"$OUT"
  echo 'P2B_PROTECTED_JAMVM_PLANNER_COMPATIBILITY=FAIL' >>"$OUT"
  echo 'RUNTIME_PATCH=FORBIDDEN' >>"$OUT"
  echo 'RUNTIME_CANDIDATE_BRANCH=DO_NOT_CREATE' >>"$OUT"
  sync 2>/dev/null || true
  exit 31
}

[ -x "$JAMVM" ] || fail JAMVM_MISSING
[ -f "$GLIBJ" ] || fail GLIBJ_MISSING
[ -f "$JAR" ] || fail PROBE_JAR_MISSING
[ -f "$REF" ] || fail REFERENCE_MISSING
[ -f "$MANIFEST" ] || fail PROBE_MANIFEST_MISSING
command -v sha256sum >/dev/null 2>&1 || fail SHA256SUM_MISSING

JB=$(sha256sum "$JAMVM" | awk '{print $1}')
GB=$(sha256sum "$GLIBJ" | awk '{print $1}')
echo "JAMVM_SHA256_BEFORE=$JB" >>"$OUT"
echo "GLIBJ_SHA256_BEFORE=$GB" >>"$OUT"
[ "$JB" = "$EXPECTED_JAMVM" ] || fail JAMVM_HASH_MISMATCH
[ "$GB" = "$EXPECTED_GLIBJ" ] || fail GLIBJ_HASH_MISMATCH

(
  cd "$ROOT" || exit 1
  sha256sum -c PROBE-SHA256SUMS.txt
) >>"$OUT" 2>&1 || fail PROBE_BUNDLE_HASH_MISMATCH

echo 'P2B_PROTECTED_RUNTIME_IDENTITY=PASS' >>"$OUT"
echo 'P2B_PROBE_BUNDLE_IDENTITY=PASS' >>"$OUT"
echo 'P2B_PROTECTED_JAMVM_PLANNER_EXECUTION=BEGIN' >>"$OUT"

"$JAMVM" -Xmx64m \
  -cp "$GLIBJ:$JAR" \
  RG35XXP2BLocalComponentPlanDiagnostic "$REF" >>"$OUT" 2>&1
RC=$?
echo "P2B_PROTECTED_JAMVM_PLANNER_EXIT_CODE=$RC" >>"$OUT"

JA=$(sha256sum "$JAMVM" | awk '{print $1}')
GA=$(sha256sum "$GLIBJ" | awk '{print $1}')
echo "JAMVM_SHA256_AFTER=$JA" >>"$OUT"
echo "GLIBJ_SHA256_AFTER=$GA" >>"$OUT"
[ "$JA" = "$EXPECTED_JAMVM" ] || fail JAMVM_HASH_CHANGED
[ "$GA" = "$EXPECTED_GLIBJ" ] || fail GLIBJ_HASH_CHANGED

[ "$RC" -eq 0 ] || fail PLANNER_EXECUTION_NONZERO
for marker in \
  'P2B_LOCAL_COMPONENT_PLAN_BOOT=PASS' \
  'P2B_LOCAL_COMPONENT_PLAN_CASES=24' \
  'P2B_LOCAL_COMPONENT_PLAN_TOTAL_COMPONENTS=52' \
  'P2B_LOCAL_COMPONENT_PLAN_SCRIPT_RUNS=65' \
  'P2B_LOCAL_COMPONENT_PLAN_MISMATCH_COUNT=0' \
  'P2B_LOCAL_COMPONENT_PLAN_DIFFERENTIAL=PASS' \
  'P2B_PLANNER_FULL_LAYOUT_PLAN=PASS_FOR_EXPANDED_CORPUS'
do
  grep -Fq "$marker" "$OUT" || fail "MISSING_MARKER:$marker"
done

echo 'P2B_PROTECTED_HASHES_AFTER=PASS' >>"$OUT"
echo 'P2B_PROTECTED_JAMVM_PLANNER_EXECUTION=PASS' >>"$OUT"
echo 'P2B_PROTECTED_JAMVM_PLANNER_COMPATIBILITY=PASS' >>"$OUT"
echo 'P2B_MODULE_DEVICE_GATE=PASS' >>"$OUT"
echo 'RUNTIME_DELTA=NONE' >>"$OUT"
echo 'RUNTIME_PATCH=FORBIDDEN' >>"$OUT"
echo 'RUNTIME_CANDIDATE_BRANCH=DO_NOT_CREATE' >>"$OUT"
echo 'PLATFORM_DEVICE_PASS=NOT_TESTED' >>"$OUT"
sync 2>/dev/null || true
exit 0
