import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

import javax.microedition.lcdui.Canvas;
import javax.microedition.lcdui.Display;
import javax.microedition.lcdui.Font;
import javax.microedition.lcdui.Graphics;
import javax.microedition.lcdui.Image;
import javax.microedition.midlet.MIDlet;
import javax.microedition.midlet.MIDletStateChangeException;

/**
 * Generated/non-commercial P2B Font/Text module exerciser.
 *
 * Expected metrics and raster-mask hashes are generated by pinned JDK8/AWT
 * using the exact hash-locked MiSans file. Device validation uses public MIDP
 * Font/Image/Graphics APIs only and never calls RG35XXCore2D directly.
 */
public final class RG35XXP2BFontTextExerciser extends MIDlet {
    private P2BCanvas canvas;

    protected void startApp() throws MIDletStateChangeException {
        if (canvas == null) {
            canvas = new P2BCanvas(this);
            Display.getDisplay(this).setCurrent(canvas);
            canvas.startTests();
        } else {
            Display.getDisplay(this).setCurrent(canvas);
        }
    }

    protected void pauseApp() { }
    protected void destroyApp(boolean unconditional) throws MIDletStateChangeException { }

    private static final class P2BCanvas extends Canvas implements Runnable {
        private static final int CASES = 360;
        private static final int W = 320;
        private static final int H = 128;
        private static final int BG = 0x00101820;
        private static final int PASS = 0x0000A840;
        private static final int FAIL = 0x00B02030;
        private static final int TEXT = 0x00FFFFFF;

        private static final int[] SIZES = {
            Font.SIZE_SMALL, Font.SIZE_MEDIUM, Font.SIZE_LARGE
        };
        private static final int[] STYLES = {
            Font.STYLE_PLAIN,
            Font.STYLE_BOLD,
            Font.STYLE_ITALIC,
            Font.STYLE_BOLD | Font.STYLE_ITALIC,
            Font.STYLE_UNDERLINED
        };
        private static final String[] STRINGS = {
            "ABCxyz09", "Tiếng Việt", "Đặng", "中文", "A\u0301", "\u0644\u0627"
        };
        private static final int[] ANCHORS = {
            Graphics.TOP | Graphics.LEFT,
            Graphics.BASELINE | Graphics.LEFT,
            Graphics.BOTTOM | Graphics.LEFT,
            Graphics.VCENTER | Graphics.HCENTER
        };

        private final RG35XXP2BFontTextExerciser app;
        private final int[] expHeight = new int[CASES];
        private final int[] expBaseline = new int[CASES];
        private final int[] expWidth = new int[CASES];
        private final int[] expCharA = new int[CASES];
        private final int[] expCharCjk = new int[CASES];
        private final int[] expInk = new int[CASES];
        private final int[] expHashA = new int[CASES];
        private final int[] expHashB = new int[CASES];

        private volatile int caseDone;
        private volatile int failureCount;
        private volatile boolean finished;
        private volatile boolean overall;
        private String firstFailure = "NONE";
        private Thread worker;

        P2BCanvas(RG35XXP2BFontTextExerciser owner) {
            app = owner;
            setFullScreenMode(true);
            overall = true;
            System.out.println("P2B_EXERCISER_BOOT=PASS");
        }

        void startTests() {
            if (worker == null) {
                worker = new Thread(this, "P2B-font-text");
                worker.start();
            }
        }

        public void run() {
            try {
                loadExpected();
                System.out.println("P2B_EXERCISER_EXPECTED_TABLE=PASS");
                int ci = 0;
                for (int zi = 0; zi < SIZES.length; zi++) {
                    for (int si = 0; si < STYLES.length; si++) {
                        Font f = Font.getFont(Font.FACE_SYSTEM, STYLES[si], SIZES[zi]);
                        for (int qi = 0; qi < STRINGS.length; qi++) {
                            for (int ai = 0; ai < ANCHORS.length; ai++) {
                                runCase(ci, f, STRINGS[qi], ANCHORS[ai], zi, si, qi, ai);
                                ci++;
                                caseDone = ci;
                                if ((ci % 12) == 0 || ci == CASES) {
                                    repaint();
                                    serviceRepaints();
                                    Thread.yield();
                                }
                            }
                        }
                    }
                }
                if (ci != CASES) failGlobal("CASE_COUNT", new IOException("count " + ci));
            } catch (Throwable t) {
                failGlobal("HARNESS", t);
            }
            finished = true;
            overall = failureCount == 0 && caseDone == CASES;
            System.out.println("P2B_EXERCISER_CASE_COUNT=" + caseDone);
            System.out.println("P2B_EXERCISER_FAILURE_COUNT=" + failureCount);
            System.out.println("P2B_EXERCISER_RESULT=" + (overall ? "PASS" : "FAIL"));
            repaint();
            serviceRepaints();
        }

        private void loadExpected() throws Exception {
            InputStream in = getClass().getResourceAsStream("/p2b/expected.tsv");
            if (in == null) throw new IOException("missing /p2b/expected.tsv");
            BufferedReader br = new BufferedReader(new InputStreamReader(in, "UTF-8"));
            int count = 0;
            String line;
            while ((line = br.readLine()) != null) {
                if (line.length() == 0 || line.charAt(0) == '#') continue;
                if (count >= CASES) throw new IOException("too many expected rows");
                String[] p = split9(line);
                if (Integer.parseInt(p[0]) != count) throw new IOException("expected order " + count);
                expHeight[count] = Integer.parseInt(p[1]);
                expBaseline[count] = Integer.parseInt(p[2]);
                expWidth[count] = Integer.parseInt(p[3]);
                expCharA[count] = Integer.parseInt(p[4]);
                expCharCjk[count] = Integer.parseInt(p[5]);
                expInk[count] = Integer.parseInt(p[6]);
                expHashA[count] = (int)Long.parseLong(p[7], 16);
                expHashB[count] = (int)Long.parseLong(p[8], 16);
                count++;
            }
            br.close();
            if (count != CASES) throw new IOException("expected row count " + count);
        }

        private void runCase(int ci, Font f, String s, int anchor,
                             int zi, int si, int qi, int ai) {
            try {
                if (f.getHeight() != expHeight[ci]) throw new IOException("height");
                if (f.getBaselinePosition() != expBaseline[ci]) throw new IOException("baseline");
                if (f.stringWidth(s) != expWidth[ci]) throw new IOException("stringWidth");
                if (f.charWidth('A') != expCharA[ci]) throw new IOException("charWidthA");
                if (f.charWidth('\u4e2d') != expCharCjk[ci]) throw new IOException("charWidthCJK");

                Image image = Image.createImage(W, H);
                Graphics g = image.getGraphics();
                g.setColor(0x00FFFFFF);
                g.fillRect(0, 0, W, H);
                g.setColor(0x00000000);
                g.setFont(f);
                int x = (anchor & Graphics.HCENTER) != 0 ? W / 2 : 24;
                int y = (anchor & Graphics.VCENTER) != 0 ? H / 2 :
                    ((anchor & Graphics.BOTTOM) != 0 ? 104 :
                    ((anchor & Graphics.BASELINE) != 0 ? 72 : 20));
                g.drawString(s, x, y, anchor);

                int[] pixels = new int[W * H];
                image.getRGB(pixels, 0, W, 0, 0, W, H);
                int ink = inkCount(pixels);
                int ha = hash1(pixels);
                int hb = hash2(pixels);
                if (ink != expInk[ci] || ha != expHashA[ci] || hb != expHashB[ci]) {
                    throw new IOException("raster " + ink + "/" + hex(ha) + "/" + hex(hb));
                }
                System.out.println("P2B_EXERCISER_CASE=" + ci +
                    " Z=" + zi + " S=" + si + " Q=" + qi + " A=" + ai +
                    " RESULT=PASS INK=" + ink + " HASH=" + hex(ha) + "/" + hex(hb));
            } catch (Throwable t) {
                failureCount++;
                overall = false;
                String detail = "case=" + ci + ":" + t.getClass().getName() + ":" + String.valueOf(t.getMessage());
                if ("NONE".equals(firstFailure)) firstFailure = detail;
                System.out.println("P2B_EXERCISER_CASE=" + ci +
                    " Z=" + zi + " S=" + si + " Q=" + qi + " A=" + ai +
                    " RESULT=FAIL DETAIL=" + detail);
            }
        }

        private void failGlobal(String where, Throwable t) {
            failureCount++;
            overall = false;
            if ("NONE".equals(firstFailure)) {
                firstFailure = where + ":" + t.getClass().getName() + ":" + String.valueOf(t.getMessage());
            }
            System.out.println("P2B_EXERCISER_GLOBAL_FAIL=" + firstFailure);
        }

        private static String[] split9(String line) throws IOException {
            String[] out = new String[9];
            int start = 0;
            for (int i = 0; i < 8; i++) {
                int tab = line.indexOf('\t', start);
                if (tab < 0) throw new IOException("bad expected row " + line);
                out[i] = line.substring(start, tab);
                start = tab + 1;
            }
            out[8] = line.substring(start);
            return out;
        }

        private static boolean white(int p) {
            return (p & 0x00FFFFFF) == 0x00FFFFFF;
        }

        private static int inkCount(int[] p) {
            int n = 0;
            for (int i = 0; i < p.length; i++) if (!white(p[i])) n++;
            return n;
        }

        private static int hash1(int[] p) {
            int h = 0x13579BDF;
            for (int i = 0; i < p.length; i++) h = h * 33 + (white(p[i]) ? 0 : 1);
            return h;
        }

        private static int hash2(int[] p) {
            int h = 0x2468ACE0;
            for (int i = 0; i < p.length; i++) {
                if (!white(p[i])) h = h * 65599 + (i + 1);
                else h = h * 65599;
            }
            return h;
        }

        private static String hex(int v) {
            String s = Integer.toHexString(v);
            StringBuffer b = new StringBuffer(8);
            for (int i = s.length(); i < 8; i++) b.append('0');
            b.append(s);
            return b.toString();
        }

        protected void paint(Graphics g) {
            int w = getWidth();
            int h = getHeight();
            g.setColor(finished ? (overall ? PASS : FAIL) : BG);
            g.fillRect(0, 0, w, h);
            g.setColor(TEXT);
            g.drawString("P2B FONT/TEXT", w / 2, 18, Graphics.HCENTER | Graphics.TOP);
            if (!finished) {
                g.drawString("RUNNING " + caseDone + "/" + CASES, w / 2, 55, Graphics.HCENTER | Graphics.TOP);
                g.drawString("JDK8 expected / public MIDP", w / 2, 82, Graphics.HCENTER | Graphics.TOP);
                g.drawString("Do not exit", w / 2, 109, Graphics.HCENTER | Graphics.TOP);
            } else if (overall) {
                g.drawString("PASS", w / 2, 58, Graphics.HCENTER | Graphics.TOP);
                g.drawString("360 font/text cases", w / 2, 88, Graphics.HCENTER | Graphics.TOP);
                g.drawString("Press any key to return", w / 2, 118, Graphics.HCENTER | Graphics.TOP);
            } else {
                g.drawString("FAIL", w / 2, 58, Graphics.HCENTER | Graphics.TOP);
                g.drawString("Failures: " + failureCount, w / 2, 88, Graphics.HCENTER | Graphics.TOP);
                g.drawString("See evidence log", w / 2, 118, Graphics.HCENTER | Graphics.TOP);
                g.drawString("Press any key to return", w / 2, 148, Graphics.HCENTER | Graphics.TOP);
            }
        }

        public void keyPressed(int keyCode) {
            if (!finished) {
                System.out.println("P2B_EXERCISER_EXIT_IGNORED=TEST_IN_PROGRESS");
                return;
            }
            System.out.println("P2B_EXERCISER_EXIT_REQUEST=PASS");
            app.notifyDestroyed();
        }
    }
}
