#!/bin/sh
# P2A image-decode module physical acceptance runner for original RG35XX.
# Never promotes DEVICE_PASS automatically.

APP="$(CDPATH= cd -- "$(dirname -- "$0")" 2>/dev/null && pwd)"
PKG="$APP/RG35XX-P2A-IMAGE-DECODE"
EVID=/mnt/mmc/RG35XX-P2A-IMAGE-DECODE-EVIDENCE
LOG="$EVID/P2A-IMAGE-DECODE-RUN.log"
SUMMARY="$EVID/P2A-IMAGE-DECODE-DEVICE-SUMMARY.txt"
JAMVM=/mnt/mmc/CFW/java/bin/jamvm
GLIBJ=/mnt/mmc/CFW/java/share/classpath/glibj.zip
EXPECTED_JAMVM=eea1b97cebfaca67b69ed365e966d80cdac22d8ff245c7a556137cfb2898ea34
EXPECTED_GLIBJ=d7abe888d2980329434c30f18c0eec124be1f02284bf9ed28e88d7242a1f2bea
EXPECTED_PLATFORM=__P2A_PLATFORM_SHA256__
EXPECTED_EXERCISER=__P2A_EXERCISER_SHA256__
EXPECTED_INPUT=69a8aeb3940bfbc234f3a562a7ae4bcaea10b50f8a8f2c38ad229a5430930f6d
EXPECTED_VIDEO=c6687c0a43b24b425af0727c928afb5414da811ecbcbbe3538928470abe8bd0d
EXPECTED_AUDIO=4522157846c33c150a85c50b4bed6f68351f1c62d54b8cd7805cbb97c5727644
EXPECTED_HEAD=__P2A_CANDIDATE_HEAD__

rm -rf "$EVID"
mkdir -p "$EVID" || exit 20
: >"$LOG"
: >"$SUMMARY"
cat >>"$SUMMARY" <<EOF_SUMMARY
PROJECT=RG35XX-AWEIGIT-R1
MODULE=P2A_IMAGE_DECODE
PHYSICAL_TEST_LEVEL=MODULE
PHYSICAL_ACCEPTANCE_SURFACE=ONE_P2A_IMAGE_DECODE_EXERCISER
CANDIDATE_HEAD=$EXPECTED_HEAD
ORIGINAL_RG35XX_REQUIRED=YES
CANONICAL_EXPECTED_SOURCE=PINNED_JDK8_IMAGEIO
PNG_FIXTURE_COUNT=150
EXPECTED_DECODE_COUNT=450
MANUAL_VISUAL_AUTHORITY=REQUIRED
DEVICE_PASS=NO_PENDING_TEST
STABLE=NO
EOF_SUMMARY

p2a_fail() {
    echo "P2A_DEVICE_PRECONDITION=FAIL:$1" >>"$LOG"
    echo "P2A_DEVICE_PRECONDITION=FAIL:$1" >>"$SUMMARY"
    echo 'P2A_DEVICE_PROGRAMMATIC_RESULT=FAIL' >>"$SUMMARY"
    echo 'DEVICE_PASS=NO' >>"$SUMMARY"
    echo 'STABLE=NO' >>"$SUMMARY"
    sync
    exit 20
}

[ -x "$JAMVM" ] || p2a_fail JAMVM_MISSING
[ -f "$GLIBJ" ] || p2a_fail GLIBJ_MISSING
[ -d "$PKG" ] || p2a_fail PAYLOAD_DIR_MISSING
for F in freej2me-rg35xx.jar RG35XX-Platform-Exerciser-P2A-Image.jar librg35xx_input.so librg35xx_video.so libaudio.so PAYLOAD-SHA256SUMS.txt P2A-MODULE-INTEGRATION-IDENTITY.txt P2A-IMAGE-DECODE-IDENTITY.txt P2A-IMAGE-EXERCISER-IDENTITY.txt PHYSICAL-PACKAGE-IDENTITY.txt; do
    [ -f "$PKG/$F" ] || p2a_fail "MISSING:$F"
done

grep -q "^CANDIDATE_HEAD=$EXPECTED_HEAD$" "$PKG/P2A-MODULE-INTEGRATION-IDENTITY.txt" || p2a_fail CANDIDATE_HEAD_MISMATCH
grep -q '^HOST_MODULE_GATE=PASS$' "$PKG/P2A-MODULE-INTEGRATION-IDENTITY.txt" || p2a_fail HOST_MODULE_GATE_NOT_PASS
grep -q '^P2A_STRICT_DIFFERENTIAL=PASS$' "$PKG/P2A-IMAGE-DECODE-IDENTITY.txt" || p2a_fail HOST_DIFFERENTIAL_NOT_PASS
grep -q '^LEGAL_MATRIX_CASES=150$' "$PKG/P2A-IMAGE-DECODE-IDENTITY.txt" || p2a_fail HOST_MATRIX_NOT_150
grep -q '^A9_PARENT=NO$' "$PKG/P2A-IMAGE-DECODE-IDENTITY.txt" || p2a_fail A9_PARENT_NOT_NO
grep -q '^COMMERCIAL_GAME_CONTENT=NO$' "$PKG/P2A-IMAGE-EXERCISER-IDENTITY.txt" || p2a_fail EXERCISER_SCOPE

grep -q '^PNG_FIXTURE_COUNT=150$' "$PKG/P2A-IMAGE-EXERCISER-IDENTITY.txt" || p2a_fail FIXTURE_COUNT
grep -q '^EXPECTED_DECODE_COUNT=450$' "$PKG/P2A-IMAGE-EXERCISER-IDENTITY.txt" || p2a_fail DECODE_COUNT
grep -q '^DIRECT_DECODER_CALL=NO$' "$PKG/P2A-IMAGE-EXERCISER-IDENTITY.txt" || p2a_fail DIRECT_DECODER_CALL

JB=$(sha256sum "$JAMVM" | awk '{print $1}')
GB=$(sha256sum "$GLIBJ" | awk '{print $1}')
PB=$(sha256sum "$PKG/freej2me-rg35xx.jar" | awk '{print $1}')
EB=$(sha256sum "$PKG/RG35XX-Platform-Exerciser-P2A-Image.jar" | awk '{print $1}')
IB=$(sha256sum "$PKG/librg35xx_input.so" | awk '{print $1}')
VB=$(sha256sum "$PKG/librg35xx_video.so" | awk '{print $1}')
AB=$(sha256sum "$PKG/libaudio.so" | awk '{print $1}')
for V in "JAMVM_SHA256_BEFORE=$JB" "GLIBJ_SHA256_BEFORE=$GB" "PLATFORM_JAR_SHA256_BEFORE=$PB" "EXERCISER_SHA256_BEFORE=$EB" "INPUT_NATIVE_SHA256_BEFORE=$IB" "VIDEO_NATIVE_SHA256_BEFORE=$VB" "AUDIO_NATIVE_SHA256_BEFORE=$AB"; do echo "$V" >>"$LOG"; done
[ "$JB" = "$EXPECTED_JAMVM" ] || p2a_fail JAMVM_HASH_MISMATCH
[ "$GB" = "$EXPECTED_GLIBJ" ] || p2a_fail GLIBJ_HASH_MISMATCH
[ "$PB" = "$EXPECTED_PLATFORM" ] || p2a_fail PLATFORM_HASH_MISMATCH
[ "$EB" = "$EXPECTED_EXERCISER" ] || p2a_fail EXERCISER_HASH_MISMATCH
[ "$IB" = "$EXPECTED_INPUT" ] || p2a_fail INPUT_HASH_MISMATCH
[ "$VB" = "$EXPECTED_VIDEO" ] || p2a_fail VIDEO_HASH_MISMATCH
[ "$AB" = "$EXPECTED_AUDIO" ] || p2a_fail AUDIO_HASH_MISMATCH
(
    cd "$PKG" || exit 1
    sha256sum -c PAYLOAD-SHA256SUMS.txt
) >>"$LOG" 2>&1 || p2a_fail PAYLOAD_HASH_MISMATCH
echo 'P2A_RUNTIME_HASH_GATE_BEFORE=PASS' >>"$LOG"

for F in PAYLOAD-SHA256SUMS.txt P2A-MODULE-INTEGRATION-IDENTITY.txt P2A-IMAGE-DECODE-IDENTITY.txt P2A-IMAGE-EXERCISER-IDENTITY.txt PHYSICAL-PACKAGE-IDENTITY.txt; do cp "$PKG/$F" "$EVID/" || p2a_fail EVIDENCE_COPY_FAIL; done
cat >"$EVID/MANUAL-OBSERVATION.txt" <<'EOF_MANUAL'
P2A_IMAGE_DECODE_MANUAL_OBSERVATION=PENDING
EXPECTED_SCREEN_TITLE=P2A IMAGE DECODE
EXPECTED_RESULT=PASS
EXPECTED_FIXTURES=150
EXPECTED_FRONTEND_DECODES=450
EXPECTED_FAILURE_INDICATOR=NONE
EXPECTED_EXIT_ACTION=PRESS_ANY_KEY_AFTER_PASS_REVIEW
EXPECTED_RETURN=GARLICOS_MENU
HUMAN_PHYSICAL_OBSERVATION=FINAL_AUTHORITY
DEVICE_PASS=NO_PENDING_REVIEW
STABLE=NO
EOF_MANUAL

DATA="$EVID/data"
RMS="$EVID/rms"
mkdir -p "$DATA" "$RMS" || p2a_fail DATA_DIR_CREATE_FAIL
echo 'P2A_DEVICE_RUN=START' >>"$LOG"
echo 'P2A_VISUAL_EXPECTATION=P2A_IMAGE_DECODE_PASS_150_FIXTURES_450_DECODES' >>"$LOG"
echo 'P2A_EXIT_EXPECTATION=PRESS_ANY_KEY_AFTER_PASS_THEN_RETURN_TO_GARLICOS' >>"$LOG"
LD_LIBRARY_PATH="$PKG${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
"$JAMVM" -Xmx64m -Drg35xx.raw2d=true -Drg35xx.native.dir="$PKG" \
    -cp "$GLIBJ:$PKG/freej2me-rg35xx.jar" org.recompile.rg35xx.RG35XXLauncher \
    "$PKG/RG35XX-Platform-Exerciser-P2A-Image.jar" 640 480 "$DATA" "$RMS" >>"$LOG" 2>&1
RC=$?
echo "P2A_RUNTIME_EXIT_CODE=$RC" >>"$LOG"

JA=$(sha256sum "$JAMVM" | awk '{print $1}')
GA=$(sha256sum "$GLIBJ" | awk '{print $1}')
PA=$(sha256sum "$PKG/freej2me-rg35xx.jar" | awk '{print $1}')
EA=$(sha256sum "$PKG/RG35XX-Platform-Exerciser-P2A-Image.jar" | awk '{print $1}')
IA=$(sha256sum "$PKG/librg35xx_input.so" | awk '{print $1}')
VA=$(sha256sum "$PKG/librg35xx_video.so" | awk '{print $1}')
AA=$(sha256sum "$PKG/libaudio.so" | awk '{print $1}')
for V in "JAMVM_SHA256_AFTER=$JA" "GLIBJ_SHA256_AFTER=$GA" "PLATFORM_JAR_SHA256_AFTER=$PA" "EXERCISER_SHA256_AFTER=$EA" "INPUT_NATIVE_SHA256_AFTER=$IA" "VIDEO_NATIVE_SHA256_AFTER=$VA" "AUDIO_NATIVE_SHA256_AFTER=$AA"; do echo "$V" >>"$LOG"; done

HASH_RESULT=PASS
[ "$JB" = "$JA" ] || HASH_RESULT=FAIL
[ "$GB" = "$GA" ] || HASH_RESULT=FAIL
[ "$PB" = "$PA" ] || HASH_RESULT=FAIL
[ "$EB" = "$EA" ] || HASH_RESULT=FAIL
[ "$IB" = "$IA" ] || HASH_RESULT=FAIL
[ "$VB" = "$VA" ] || HASH_RESULT=FAIL
[ "$AB" = "$AA" ] || HASH_RESULT=FAIL
[ "$JA" = "$EXPECTED_JAMVM" ] || HASH_RESULT=FAIL
[ "$GA" = "$EXPECTED_GLIBJ" ] || HASH_RESULT=FAIL
[ "$PA" = "$EXPECTED_PLATFORM" ] || HASH_RESULT=FAIL
[ "$EA" = "$EXPECTED_EXERCISER" ] || HASH_RESULT=FAIL
[ "$IA" = "$EXPECTED_INPUT" ] || HASH_RESULT=FAIL
[ "$VA" = "$EXPECTED_VIDEO" ] || HASH_RESULT=FAIL
[ "$AA" = "$EXPECTED_AUDIO" ] || HASH_RESULT=FAIL
echo "P2A_PROTECTED_HASHES=$HASH_RESULT" >>"$LOG"
if [ "$RC" -eq 0 ]; then echo 'P2A_NORMAL_EXIT=PASS' >>"$LOG"; else echo 'P2A_NORMAL_EXIT=FAIL' >>"$LOG"; fi

PROGRAMMATIC=PASS
[ "$RC" -eq 0 ] || PROGRAMMATIC=FAIL
[ "$HASH_RESULT" = PASS ] || PROGRAMMATIC=FAIL
grep -q '^RG35XX_A7_AUDIO_BRIDGE=LOADED DEVICE_INIT=LAZY BACKEND=SDL1_MIXER$' "$LOG" || PROGRAMMATIC=FAIL
grep -q '^P2A_EXERCISER_BOOT=PASS$' "$LOG" || PROGRAMMATIC=FAIL
grep -q '^P2A_EXERCISER_EXPECTED_TABLE=PASS$' "$LOG" || PROGRAMMATIC=FAIL
grep -q '^P2A_EXERCISER_FIXTURE_COUNT=150$' "$LOG" || PROGRAMMATIC=FAIL
grep -q '^P2A_EXERCISER_FRONTEND_COUNT=3$' "$LOG" || PROGRAMMATIC=FAIL
grep -q '^P2A_EXERCISER_DECODE_COUNT=450$' "$LOG" || PROGRAMMATIC=FAIL
grep -q '^P2A_EXERCISER_FAILURE_COUNT=0$' "$LOG" || PROGRAMMATIC=FAIL
grep -q '^P2A_EXERCISER_RESULT=PASS$' "$LOG" || PROGRAMMATIC=FAIL
grep -q '^P2A_EXERCISER_EXIT_REQUEST=PASS$' "$LOG" || PROGRAMMATIC=FAIL
[ "$(grep -c ' RESULT=PASS HASH=' "$LOG")" -eq 450 ] || PROGRAMMATIC=FAIL
if grep -q ' RESULT=FAIL ' "$LOG"; then PROGRAMMATIC=FAIL; fi
grep -q '^RG35XX_A3_SDL_DRIVER=fbcon$' "$LOG" || PROGRAMMATIC=FAIL
grep -q '^RG35XX_A3_SURFACE=640x480 ' "$LOG" || PROGRAMMATIC=FAIL
echo "P2A_DEVICE_PROGRAMMATIC_RESULT=$PROGRAMMATIC" >>"$LOG"

cat >>"$SUMMARY" <<EOF_RESULT
P2A_RUNTIME_EXIT_CODE=$RC
P2A_PROTECTED_HASHES=$HASH_RESULT
P2A_DEVICE_PROGRAMMATIC_RESULT=$PROGRAMMATIC
P2A_IMAGE_DECODE_MANUAL_OBSERVATION=PENDING
DEVICE_PASS=NO_PENDING_MANUAL_REVIEW
STABLE=NO
EOF_RESULT
if [ "$RC" -eq 0 ]; then echo 'P2A_NORMAL_EXIT=PASS' >>"$SUMMARY"; else echo 'P2A_NORMAL_EXIT=FAIL' >>"$SUMMARY"; fi
sync
[ "$PROGRAMMATIC" = PASS ] && exit 0
exit 2
