param([Parameter(Mandatory=$false, Position=0)][string]$SdRoot,[switch]$SelfTest)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function Count-Matches([object[]]$a,[string]$s){return @($a|Select-String -SimpleMatch $s).Count}
function Sha([string]$p){if(!(Test-Path -LiteralPath $p -PathType Leaf)){return $null};return (Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash.ToLowerInvariant()}
if($SelfTest){$x=@('a marker','b','marker c');if((Count-Matches $x 'marker')-ne 2){throw 'count selftest'};Write-Output 'SELFTEST_COUNT=PASS';exit 0}
if([string]::IsNullOrWhiteSpace($SdRoot)){$SdRoot=Read-Host 'Nhap ky tu o SD RG35XX'};$SdRoot=$SdRoot.Trim().Trim('"');if($SdRoot-match'^[A-Za-z]$'){$SdRoot=$SdRoot+':'};if($SdRoot-match'^[A-Za-z]:$'){$SdRoot=$SdRoot+'\'};if(!(Test-Path -LiteralPath $SdRoot -PathType Container)){throw "SD root not found: $SdRoot"};$Sd=(Resolve-Path -LiteralPath $SdRoot).Path
$stamp=Get-Date -Format 'yyyyMMdd-HHmmss';$out=Join-Path $PSScriptRoot ("R2C-AUDIO-R1-AB-EVIDENCE-"+$stamp);New-Item -ItemType Directory -Force -Path $out|Out-Null
foreach($n in @('R2C-AUDIO-R1-AB-INSTALL-RESULT.txt','R2C-AUDIO-R1-AB-PRECHECK.txt','freej2me-java-error.log','freej2me-vc3-early.log','freej2me-core.log','freej2me-java-control.log')){$p=Join-Path $Sd $n;if(Test-Path -LiteralPath $p -PathType Leaf){Copy-Item -LiteralPath $p -Destination $out -Force}}
$hash=@();foreach($rel in @('CFW\java\bin\jamvm','CFW\java\share\classpath\glibj.zip','CFW\retroarch\.retroarch\cores\freej2me_plus_libretro.so','BIOS\freej2me.sf2','BIOS\freej2me-lr.jar','BIOS\freej2me_plus-lr.jar','CFW\java\share\freej2me\freej2me-lr.jar','CFW\retroarch\.retroarch\system\freej2me-lr.jar','CFW\retroarch\system\freej2me-lr.jar')){$p=Join-Path $Sd $rel;if(Test-Path -LiteralPath $p -PathType Leaf){$hash+=("$rel="+(Sha $p))}};$hash|Set-Content -LiteralPath (Join-Path $out 'DEVICE-HASHES.txt') -Encoding ASCII
$sum=@('CHECKPOINT=R2C-AUDIO-R1-AB','PRIMARY_VARIABLE=AUDIO_OWNERSHIP_ONLY','FONT_BASELINE=R2C','TRANSPARENCY_CHANGE=NONE','STABLE=NO')
$j=Join-Path $Sd 'freej2me-java-error.log';if(Test-Path -LiteralPath $j -PathType Leaf){$l=@(Get-Content -LiteralPath $j);$sum+=("JAVA_LINES="+$l.Count);$sum+=("FONT_READY="+(Count-Matches $l 'RG35XX-R2D-FONT: ready bytes=727008'));$sum+=("ZONE_AIOOBE="+(Count-Matches $l 'Zone.combineWithSubGlyph'));$sum+=("RENDER_SCANLINE_NPE="+(Count-Matches $l 'AbstractGraphics2D.renderScanline'));$sum+=("GETSEQUENCER_ERRORS="+(Count-Matches $l 'NoSuchMethodError: getSequencer'));$sum+=("CLIP_ERRORS="+(Count-Matches $l 'LineUnavailableException'));$sum+=("MEDIAWARMUP="+(Count-Matches $l 'RG35XX-MediaWarmup'));$sum+=("DEV_SND_SEQ="+(Count-Matches $l '/dev/snd/seq'));$sum+=("IMAGE_NORMALIZE="+(Count-Matches $l 'RG35XX-R2A-IMAGE-NORMALIZE'));$sum+=("FRAME_BIND_MISMATCH_TRUE="+(Count-Matches $l 'mismatch=true'))}
$allLogs=@();foreach($n in @('freej2me-core.log','freej2me-vc3-early.log','freej2me-java-error.log')){$p=Join-Path $Sd $n;if(Test-Path -LiteralPath $p -PathType Leaf){$allLogs+=@(Get-Content -LiteralPath $p)}};$sum+=("ASYNC_CALLBACK_REGISTER="+(Count-Matches $allLogs 'RG35XX-AUDIO: async callback registered='));$sum+=("WORKER_START="+(Count-Matches $allLogs 'RG35XX-AUDIO: worker START ring=16384 target=3072 chunk=1470'));$sum+=("AUDIO_UNDERRUN="+(Count-Matches $allLogs 'underrun'));$sum+=("AUDIO_REPRIME="+(Count-Matches $allLogs 're-prime'));$sum+=("END_OF_MEDIA="+(Count-Matches $allLogs 'END_OF_MEDIA'))
$e=Join-Path $Sd 'freej2me-vc3-early.log';if(Test-Path -LiteralPath $e -PathType Leaf){$l=@(Get-Content -LiteralPath $e);$sum+=("CORE_INIT="+(Count-Matches $l 'B4 CORE_INIT'));$sum+=("JAVA_READY="+(Count-Matches $l 'B4 JAVA_READY'));$sum+=("LOAD_GAME="+(Count-Matches $l 'B4 LOAD_GAME_ENTER'));$sum+=("FIRST_FRAME="+(Count-Matches $l 'FIRST_FRAME'));$sum+=("CORE_DEINIT="+(Count-Matches $l 'B4 CORE_DEINIT'))}
$sum+=@('MANUAL_AUDIO_CHECK=report audible/silent per game','MANUAL_FREEZE_CHECK=report exact point and whether frames/input continue','MANUAL_BACKGROUND_CHECK=expected unchanged in this checkpoint','MANUAL_EXIT_CHECK=normal exit/hard reset','TEST_GAMES=NinjaSchool2,KDTT,Real Football 2015')
$sum|Set-Content -LiteralPath (Join-Path $out 'SUMMARY.txt') -Encoding ASCII
Compress-Archive -Path (Join-Path $out '*') -DestinationPath ($out+'.zip') -Force;Write-Host "COLLECT PASS: $out.zip"
