param([Parameter(Mandatory=$false, Position=0)][string]$SdRoot,[switch]$SelfTest)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
function Count-Matches([object[]]$InputLines,[string]$Needle){return @($InputLines|Select-String -SimpleMatch $Needle).Count}
function Sha([string]$p){if(!(Test-Path -LiteralPath $p -PathType Leaf)){return $null};return (Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash.ToLowerInvariant()}
if($SelfTest){$a=@('x','worker START','worker START');if((Count-Matches $a 'worker START') -ne 2){throw 'count selftest'};Write-Output 'SELFTEST_COUNT=PASS';exit 0}
if([string]::IsNullOrWhiteSpace($SdRoot)){$SdRoot=Read-Host 'Nhap ky tu o SD RG35XX'}
$SdRoot=$SdRoot.Trim().Trim('"');if($SdRoot -match '^[A-Za-z]$'){$SdRoot=$SdRoot+':'};if($SdRoot -match '^[A-Za-z]:$'){$SdRoot=$SdRoot+'\'}
if(!(Test-Path -LiteralPath $SdRoot -PathType Container)){throw "SD root not found: $SdRoot"};$Sd=(Resolve-Path -LiteralPath $SdRoot).Path
$stamp=Get-Date -Format 'yyyyMMdd-HHmmss';$out=Join-Path $PSScriptRoot ("RG35XX-R2B-AUDIO-EVIDENCE-"+$stamp);New-Item -ItemType Directory -Force -Path $out|Out-Null
foreach($n in @('RG35XX-CLEAN-R2B-AUDIO-INSTALL-RESULT.txt','RG35XX-R2B-AUDIO-PRECHECK.txt','freej2me-vc3-early.log','freej2me-core.log','freej2me-java-error.log','freej2me-java-control.log')){$p=Join-Path $Sd $n;if(Test-Path -LiteralPath $p -PathType Leaf){Copy-Item -LiteralPath $p -Destination $out -Force}}
$hash=@();foreach($rel in @('CFW\java\bin\jamvm','CFW\java\share\classpath\glibj.zip','CFW\retroarch\.retroarch\cores\freej2me_plus_libretro.so','BIOS\freej2me.sf2','BIOS\freej2me-lr.jar','BIOS\freej2me_plus-lr.jar','CFW\java\share\freej2me\freej2me-lr.jar','CFW\retroarch\.retroarch\system\freej2me-lr.jar','CFW\retroarch\system\freej2me-lr.jar')){$p=Join-Path $Sd $rel;if(Test-Path -LiteralPath $p -PathType Leaf){$hash+=("$rel="+(Sha $p))}}
$hash|Set-Content -LiteralPath (Join-Path $out 'DEVICE-HASHES.txt') -Encoding ASCII
$summary=@('CHECKPOINT=RG35XX-CLEAN-R2B-AUDIO','PRIMARY_VARIABLE=AUDIO_OWNERSHIP_ONLY','BUILD_PASS=YES','DEVICE_PASS=NO_DEVICE_TEST_PENDING','STABLE=NO')
$core=Join-Path $Sd 'freej2me-core.log';if(Test-Path -LiteralPath $core -PathType Leaf){$l=@(Get-Content -LiteralPath $core);$summary+=("CORE_LOG_LINES="+$l.Count);$summary+=("ASYNC_CALLBACK_REGISTER="+(Count-Matches $l 'RG35XX-AUDIO: async callback registered='));$summary+=("WORKER_START="+(Count-Matches $l 'RG35XX-AUDIO: worker START ring=16384 target=3072 chunk=1470'));$summary+=("PRIMED="+(Count-Matches $l 'PRIMED'));$summary+=("UNDERRUN="+(Count-Matches $l 'underrun'));$summary+=("REPRIME="+(Count-Matches $l 're-prime'));$summary+=("NATIVE_END="+(Count-Matches $l 'native END'));$summary+=("END_OF_MEDIA="+(Count-Matches $l 'END_OF_MEDIA'));$summary+=("SOUNDFONT="+(Count-Matches $l 'SoundFont'))}
$java=Join-Path $Sd 'freej2me-java-error.log';if(Test-Path -LiteralPath $java -PathType Leaf){$j=@(Get-Content -LiteralPath $java);$summary+=("JAVA_LOG_LINES="+$j.Count);$summary+=("GETSEQUENCER_ERRORS="+(Count-Matches $j 'NoSuchMethodError: getSequencer'));$summary+=("CLIP_ERRORS="+(Count-Matches $j 'LineUnavailableException'));$summary+=("MEDIAWARMUP="+(Count-Matches $j 'RG35XX-MediaWarmup'));$summary+=("DEV_SND_SEQ="+(Count-Matches $j '/dev/snd/seq'));$summary+=("MEDIA_EVENT="+(Count-Matches $j 'RG35XX-VC7R3-MEDIA-EVENT'))}
$early=Join-Path $Sd 'freej2me-vc3-early.log';if(Test-Path -LiteralPath $early -PathType Leaf){$e=@(Get-Content -LiteralPath $early);$summary+=("CORE_INIT="+(Count-Matches $e 'B4 CORE_INIT'));$summary+=("JAVA_READY="+(Count-Matches $e 'B4 JAVA_READY'));$summary+=("LOAD_GAME="+(Count-Matches $e 'B4 LOAD_GAME_ENTER'));$summary+=("CORE_DEINIT="+(Count-Matches $e 'B4 CORE_DEINIT'))}
$summary+=@('MANUAL_AUDIO_CHECK=report audible/silent for each tested game','MANUAL_RENDER_CHECK=report unchanged/corrupt','MANUAL_EXIT_CHECK=report normal exit/hard reset','TEST_GAMES=NinjaSchool2,KDTT,Real Football 2015 or Zombie Infection')
$summary|Set-Content -LiteralPath (Join-Path $out 'R2B-AUDIO-SUMMARY.txt') -Encoding ASCII
Compress-Archive -Path (Join-Path $out '*') -DestinationPath ($out+'.zip') -Force;Write-Host "COLLECT R2B AUDIO PASS: $out.zip"
