#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
fail(){ echo "P2A_EXERCISER_BUILD_FAIL=$*" >&2; exit 1; }

JAVA8="${JAVA8:-${JAVA_HOME:-}}"
[ -n "$JAVA8" ] || fail "JAVA8/JAVA_HOME not set"
for t in javac java jar; do [ -x "$JAVA8/bin/$t" ] || fail "$t missing"; done

OUT="$ROOT/out/p2a-image-decode-candidate"
PLATFORM="$OUT/freej2me-rg35xx.jar"
SRC="$ROOT/tests/p2a/exerciser/RG35XXP2AImageDecodeExerciser.java"
BUILD="$ROOT/build/p2a-image-exerciser"
RES="$BUILD/resources"
JAROUT="$OUT/RG35XX-Platform-Exerciser-P2A-Image.jar"
IDENTITY="$OUT/P2A-IMAGE-EXERCISER-IDENTITY.txt"
FIXTURE_MANIFEST="$RES/p2a/fixture-manifest.tsv"
EXPECTED="$RES/p2a/expected.tsv"

[ -f "$PLATFORM" ] || fail "P2A candidate platform jar missing"
[ -f "$SRC" ] || fail "exerciser source missing"
rm -rf "$BUILD"
mkdir -p "$BUILD/classes" "$BUILD/host" "$RES/p2a"

# Generate the complete legal PNG matrix. Expected pixels are NOT generated by
# this Python code; pinned JDK8 ImageIO below is the canonical expected source.
python3 - "$RES/p2a" "$FIXTURE_MANIFEST" <<'PY'
import os, struct, sys, zlib
out, manifest = sys.argv[1:]
W, H = 9, 8
specs = [
    (0, [1,2,4,8,16]),
    (2, [8,16]),
    (3, [1,2,4,8]),
    (4, [8,16]),
    (6, [8,16]),
]
channels = {0:1, 2:3, 3:1, 4:2, 6:4}
passes = [(0,0,8,8),(4,0,8,8),(0,4,4,8),(2,0,4,4),(0,2,2,4),(1,0,2,2),(0,1,1,2)]

def chunk(t, data):
    tb=t.encode('ascii')
    return struct.pack('>I',len(data))+tb+data+struct.pack('>I',zlib.crc32(tb+data)&0xffffffff)

def maxv(depth): return (1<<depth)-1 if depth < 16 else 65535

def samples(ct, depth, x, y):
    m=maxv(depth)
    if ct == 0:
        return [((x*3 + y*5 + 1) * (m if m < 17 else 257) + x + y) % (m+1)]
    if ct == 2:
        return [
            (x*997 + y*313 + 0x1234) % (m+1),
            (x*557 + y*911 + 0x3456) % (m+1),
            (x*211 + y*733 + 0x5678) % (m+1),
        ]
    if ct == 3:
        return [(x + 3*y + (x*y)) % (m+1)]
    if ct == 4:
        return [
            (x*701 + y*383 + 0x1111) % (m+1),
            (x*193 + y*821 + 0x2222) % (m+1),
        ]
    return [
        (x*997 + y*313 + 0x1234) % (m+1),
        (x*557 + y*911 + 0x3456) % (m+1),
        (x*211 + y*733 + 0x5678) % (m+1),
        (x*389 + y*677 + 0x789a) % (m+1),
    ]

def pack_values(vals, depth):
    if depth == 8:
        return bytes(v & 0xff for v in vals)
    if depth == 16:
        b=bytearray()
        for v in vals: b.extend(((v>>8)&0xff, v&0xff))
        return bytes(b)
    b=bytearray((len(vals)*depth + 7)//8)
    bit=0
    mask=(1<<depth)-1
    for v in vals:
        byte=bit>>3
        shift=8-depth-(bit&7)
        b[byte] |= (v & mask) << shift
        bit += depth
    return bytes(b)

def paeth(a,b,c):
    p=a+b-c; pa=abs(p-a); pb=abs(p-b); pc=abs(p-c)
    if pa <= pb and pa <= pc: return a
    if pb <= pc: return b
    return c

def filter_row(raw, prev, ft, bpp):
    if ft == 0: return raw
    out=bytearray(len(raw))
    for i,v in enumerate(raw):
        left = raw[i-bpp] if i >= bpp else 0
        up = prev[i] if prev is not None else 0
        ul = prev[i-bpp] if prev is not None and i >= bpp else 0
        if ft == 1: pred=left
        elif ft == 2: pred=up
        elif ft == 3: pred=(left+up)//2
        elif ft == 4: pred=paeth(left,up,ul)
        else: raise ValueError(ft)
        out[i]=(v-pred)&0xff
    return bytes(out)

def row_bytes(ct, depth, coords):
    vals=[]
    for x,y in coords: vals.extend(samples(ct,depth,x,y))
    return pack_values(vals, depth)

def scan_data(ct, depth, interlace, ft):
    bpp=max(1,(channels[ct]*depth+7)//8)
    data=bytearray()
    if not interlace:
        prev=None
        for y in range(H):
            raw=row_bytes(ct,depth,[(x,y) for x in range(W)])
            data.append(ft); data.extend(filter_row(raw,prev,ft,bpp)); prev=raw
    else:
        for sx,sy,dx,dy in passes:
            xs=list(range(sx,W,dx)); ys=list(range(sy,H,dy))
            if not xs or not ys: continue
            prev=None
            for y in ys:
                raw=row_bytes(ct,depth,[(x,y) for x in xs])
                data.append(ft); data.extend(filter_row(raw,prev,ft,bpp)); prev=raw
    return bytes(data)

def palette(depth):
    n=1<<depth
    p=bytearray(); a=bytearray()
    for i in range(n):
        p.extend(((i*73+19)&255,(i*151+47)&255,(i*199+91)&255))
        a.append((i*41+17)&255)
    if n > 1: a[1]=0
    return bytes(p),bytes(a)

def trns(ct, depth):
    s=samples(ct,depth,0,0)
    if ct == 0: return struct.pack('>H',s[0])
    if ct == 2: return struct.pack('>HHH',s[0],s[1],s[2])
    return None

def make_png(ct,depth,interlace,ft):
    png=b'\x89PNG\r\n\x1a\n'
    png += chunk('IHDR',struct.pack('>IIBBBBB',W,H,depth,ct,0,0,interlace))
    if ct == 3:
        p,a=palette(depth); png += chunk('PLTE',p); png += chunk('tRNS',a)
    elif ct in (0,2):
        png += chunk('tRNS',trns(ct,depth))
    payload=zlib.compress(scan_data(ct,depth,interlace,ft),9)
    png += chunk('IDAT',payload)+chunk('IEND',b'')
    return png

rows=[]; idx=0
for ct,depths in specs:
    for depth in depths:
        for interlace in (0,1):
            for ft in range(5):
                name='f%03d.png'%idx
                data=make_png(ct,depth,interlace,ft)
                with open(os.path.join(out,name),'wb') as f: f.write(data)
                rows.append('%s\tCT%d\tBD%d\tI%d\tF%d\t%d\n'%(name,ct,depth,interlace,ft,len(data)))
                idx += 1
if idx != 150: raise SystemExit('fixture count %d'%idx)
with open(manifest,'w',encoding='ascii') as f:
    f.write('FILE\tCOLOR_TYPE\tBIT_DEPTH\tINTERLACE\tFILTER\tBYTES\n')
    f.writelines(rows)
print('P2A_EXERCISER_FIXTURE_GENERATION=PASS')
print('P2A_EXERCISER_FIXTURE_COUNT=%d'%idx)
PY

cat > "$BUILD/P2AExpectedGenerator.java" <<'JAVA'
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.PrintWriter;
import javax.imageio.ImageIO;

public final class P2AExpectedGenerator {
    private static int hash1(int[] p) {
        int h=0x13579BDF;
        for (int i=0;i<p.length;i++) h=h*33+p[i];
        return h;
    }
    private static int hash2(int[] p) {
        int h=0x2468ACE0;
        for (int i=0;i<p.length;i++) h=h*65599+(p[i]^(p[i]>>>16));
        return h;
    }
    private static String hex(int v) {
        String s=Integer.toHexString(v);
        StringBuffer b=new StringBuffer(8);
        for(int i=s.length();i<8;i++) b.append('0');
        b.append(s); return b.toString();
    }
    private static String name(int i) {
        if(i<10) return "f00"+i+".png";
        if(i<100) return "f0"+i+".png";
        return "f"+i+".png";
    }
    public static void main(String[] a) throws Exception {
        File dir=new File(a[0]);
        PrintWriter out=new PrintWriter(a[1],"UTF-8");
        out.println("# PINNED_JDK8_IMAGEIO_EXPECTED");
        for(int i=0;i<150;i++) {
            String n=name(i);
            BufferedImage img=ImageIO.read(new File(dir,n));
            if(img==null) throw new RuntimeException("ImageIO null "+n);
            int w=img.getWidth(),h=img.getHeight();
            int[] p=img.getRGB(0,0,w,h,null,0,w);
            out.println(n+"\t"+w+"\t"+h+"\t"+hex(hash1(p))+"\t"+hex(hash2(p)));
        }
        out.close();
    }
}
JAVA

"$JAVA8/bin/javac" -encoding UTF-8 -source 1.6 -target 1.6 \
  -bootclasspath "$JAVA8/jre/lib/rt.jar" -d "$BUILD/host" "$BUILD/P2AExpectedGenerator.java"
"$JAVA8/bin/java" -Djava.awt.headless=true -cp "$BUILD/host" P2AExpectedGenerator "$RES/p2a" "$EXPECTED"
[ "$(grep -vc '^#' "$EXPECTED")" -eq 150 ] || fail "JDK8 expected row count"
echo P2A_EXERCISER_JDK8_EXPECTED=PASS

"$JAVA8/bin/javac" -encoding UTF-8 -source 1.6 -target 1.6 \
  -bootclasspath "$JAVA8/jre/lib/rt.jar" -classpath "$PLATFORM" \
  -d "$BUILD/classes" "$SRC"

cat > "$BUILD/MANIFEST.MF" <<'EOF_MANIFEST'
Manifest-Version: 1.0
MIDlet-Name: RG35XX P2A Image Decode Exerciser
MIDlet-Version: 1.0.0
MIDlet-Vendor: RG35XX Platform Reconstruction
MIDlet-1: RG35XX P2A Image Decode Exerciser,,RG35XXP2AImageDecodeExerciser
MicroEdition-Configuration: CLDC-1.0
MicroEdition-Profile: MIDP-2.0
EOF_MANIFEST

rm -f "$JAROUT"
"$JAVA8/bin/jar" cfm "$JAROUT" "$BUILD/MANIFEST.MF" -C "$BUILD/classes" . -C "$RES" p2a

python3 - "$JAROUT" <<'PY'
import sys,zipfile
jar=sys.argv[1]
required={
 'RG35XXP2AImageDecodeExerciser.class',
 'RG35XXP2AImageDecodeExerciser$P2ACanvas.class',
 'META-INF/MANIFEST.MF',
 'p2a/expected.tsv',
 'p2a/fixture-manifest.tsv',
}
majors=set()
with zipfile.ZipFile(jar) as z:
    names=set(z.namelist()); missing=required-names
    if missing: raise SystemExit('P2A_EXERCISER_JAR_GATE_FAIL missing='+repr(sorted(missing)))
    pngs=sorted(n for n in names if n.startswith('p2a/f') and n.endswith('.png'))
    if len(pngs)!=150: raise SystemExit('P2A_EXERCISER_JAR_GATE_FAIL png-count=%d'%len(pngs))
    classes=sorted(n for n in names if n.endswith('.class'))
    expected_classes=['RG35XXP2AImageDecodeExerciser$P2ACanvas.class','RG35XXP2AImageDecodeExerciser.class']
    if classes!=expected_classes: raise SystemExit('P2A_EXERCISER_JAR_GATE_FAIL classes='+repr(classes))
    blob=b''.join(z.read(n) for n in classes)
    for marker in (b'P2A_EXERCISER_BOOT=PASS',b'P2A_EXERCISER_RESULT=',b'P2A_EXERCISER_FIXTURE_COUNT=',b'BYTES',b'STREAM',b'RESOURCE'):
        if marker not in blob: raise SystemExit('P2A_EXERCISER_MARKER_GATE_FAIL '+repr(marker))
    if b'RG35XXCore2D' in blob: raise SystemExit('P2A_EXERCISER_DIRECT_DECODER_CALL_FORBIDDEN')
    for n in classes:
        b=z.read(n)
        if b[:4]!=b'\xca\xfe\xba\xbe': raise SystemExit('bad class magic '+n)
        major=int.from_bytes(b[6:8],'big'); majors.add(major)
        if major>50: raise SystemExit('P2A_EXERCISER_JAVA6_FAIL %s major=%d'%(n,major))
print('P2A_EXERCISER_CLASS_MAJORS='+','.join(map(str,sorted(majors))))
print('P2A_EXERCISER_JAVA6_GATE=PASS')
print('P2A_EXERCISER_RESOURCE_COUNT=150')
print('P2A_EXERCISER_DIRECT_DECODER_CALL=NO')
PY

EX_SHA="$(sha256sum "$JAROUT"|awk '{print $1}')"
FIXTURE_SHA="$(python3 - "$RES/p2a" <<'PY'
import hashlib,os,sys
root=sys.argv[1]; h=hashlib.sha256()
for n in sorted(os.listdir(root)):
    p=os.path.join(root,n)
    if not os.path.isfile(p): continue
    b=open(p,'rb').read(); nb=n.encode('utf-8')
    h.update(len(nb).to_bytes(4,'big'));h.update(nb);h.update(len(b).to_bytes(8,'big'));h.update(b)
print(h.hexdigest())
PY
)"
cat > "$IDENTITY" <<EOF_ID
PROJECT=RG35XX-AWEIGIT-R1
MODULE=P2A_IMAGE_DECODE
ARTIFACT=RG35XX-Platform-Exerciser-P2A-Image.jar
SOURCE=tests/p2a/exerciser/RG35XXP2AImageDecodeExerciser.java
CANONICAL_EXPECTED_SOURCE=PINNED_JDK8_IMAGEIO
DECLARED_FORMAT=PNG
PNG_FIXTURE_COUNT=150
PNG_FILTERS=0,1,2,3,4
PNG_INTERLACE=0,1
API_FRONTENDS=BYTE_ARRAY,INPUT_STREAM,RESOURCE_NAME
EXPECTED_DECODE_COUNT=450
FIXTURE_SET_SHA256=$FIXTURE_SHA
JAVA6_GATE=PASS
DIRECT_DECODER_CALL=NO
COMMERCIAL_GAME_CONTENT=NO
EXERCISER_SHA256=$EX_SHA
PHYSICAL_TEST_REQUIRED=YES_ORIGINAL_RG35XX
PHYSICAL_TEST_LEVEL=MODULE
DEVICE-PASS=NO
STABLE=NO
EOF_ID

echo P2A_EXERCISER_SHA256="$EX_SHA"
echo P2A_EXERCISER_FIXTURE_SET_SHA256="$FIXTURE_SHA"
echo P2A_EXERCISER_BUILD=PASS
cat "$IDENTITY"
