#!/bin/sh
set -eu

# RGJ-RC1-011K/011M/011N — GNU Classpath/runtime + native Make overlay gate.
# Operates only on disposable assembled trees.
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
: "${RG35XX_ASSEMBLY_ROOT:?set RG35XX_ASSEMBLY_ROOT to the 011J assembled FreeJ2ME tree}"
: "${RG35XX_CLASSPATH_ROOT:?set RG35XX_CLASSPATH_ROOT to GNU Classpath 0.99 source}"
: "${RG35XX_RUNTIME_ASSEMBLY_ROOT:?set RG35XX_RUNTIME_ASSEMBLY_ROOT to a disposable GNU Classpath output tree}"
: "${RG35XX_FONT_FILE:?set RG35XX_FONT_FILE to materialized DejaVuSans.ttf}"
: "${RG35XX_FONT_RUNTIME_PATH:?set RG35XX_FONT_RUNTIME_PATH to the absolute target-device DejaVuSans.ttf path}"

fail() { echo "RC1 RUNTIME OVERLAY: FAIL: $*" >&2; exit 1; }
note() { echo "RC1 RUNTIME OVERLAY: $*"; }

[ -f "$RG35XX_ASSEMBLY_ROOT/src/libretro/freej2me_libretro.c" ] || fail "011J assembled FreeJ2ME tree missing"
[ -f "$RG35XX_ASSEMBLY_ROOT/src/libretro/rg35xx/rc1_sources.mk" ] || fail "011J native source manifest missing"
[ -f "$RG35XX_CLASSPATH_ROOT/gnu/java/awt/peer/headless/HeadlessToolkit.java" ] || fail "GNU Classpath 0.99 HeadlessToolkit missing"
[ -s "$RG35XX_FONT_FILE" ] || fail "DejaVu font input missing"
[ "$RG35XX_RUNTIME_ASSEMBLY_ROOT" != "$RG35XX_CLASSPATH_ROOT" ] || fail "runtime assembly must not mutate Classpath source"
case "$RG35XX_FONT_RUNTIME_PATH" in /*) ;; *) fail "font runtime path must be absolute" ;; esac

RG35XX_CLASSPATH_ROOT="$RG35XX_CLASSPATH_ROOT" RG35XX_FONT_FILE="$RG35XX_FONT_FILE" \
  sh "$ROOT/scripts/rc1_classpath_preflight.sh"

rm -rf "$RG35XX_RUNTIME_ASSEMBLY_ROOT"
mkdir -p "$RG35XX_RUNTIME_ASSEMBLY_ROOT"
( cd "$RG35XX_CLASSPATH_ROOT" && tar --exclude=.git -cf - . ) | ( cd "$RG35XX_RUNTIME_ASSEMBLY_ROOT" && tar -xf - )

RG35XX_CLASSPATH_ROOT="$RG35XX_RUNTIME_ASSEMBLY_ROOT" \
RG35XX_FONT_FILE="$RG35XX_FONT_FILE" \
RG35XX_FONT_RUNTIME_PATH="$RG35XX_FONT_RUNTIME_PATH" \
  sh "$ROOT/runtime/classpath/apply_rg35xx_font_overlay.sh"
PEER="$RG35XX_RUNTIME_ASSEMBLY_ROOT/gnu/java/awt/peer/headless/HeadlessToolkit.java"
OT="$RG35XX_RUNTIME_ASSEMBLY_ROOT/gnu/java/awt/font/OpenTypeFontPeer.java"
FONT_STAGE="$RG35XX_RUNTIME_ASSEMBLY_ROOT/resource/rg35xx/DejaVuSans.ttf"
grep -q 'new OpenTypeFontPeer(logical, attrKey)' "$PEER" || fail "concrete HeadlessToolkit FontPeer overlay missing"
grep -q 'private synchronized ClasspathFontPeer rg35xxFontPeer' "$PEER" || fail "font peer cache synchronization missing"
grep -q 'RG35XX: unable to initialize OpenType font peer' "$OT" || fail "OpenTypeFontPeer is not fail-closed"
[ -s "$FONT_STAGE" ] || fail "staged DejaVu runtime payload missing"

cat > "$RG35XX_ASSEMBLY_ROOT/src/libretro/rg35xx/rc1_make_overlay.mk" <<'EOF'
# Generated by RGJ-RC1-011K/011M. Include from pinned src/libretro/Makefile.common.
include rg35xx/rc1_sources.mk
SOURCES_C += $(RG35XX_NATIVE_SRCS)
INCFLAGS += $(RG35XX_NATIVE_CFLAGS)
# Target toolchain must supply pthread/math equivalents. Do not infer host flags as target proof.
RG35XX_REQUIRED_LIBS := pthread m
EOF

# 011N deployment manifest: build-time source and target runtime destination are distinct.
# Packaging/deployment must copy SOURCE to TARGET exactly; the Classpath fonts.properties
# points to TARGET and must never contain a disposable build-host path.
FONT_SHA=$(sha256sum "$FONT_STAGE" | awk '{print $1}')
cat > "$RG35XX_ASSEMBLY_ROOT/rg35xx_runtime_files.list" <<EOF
TYPE=font
SOURCE=$FONT_STAGE
TARGET=$RG35XX_FONT_RUNTIME_PATH
SHA256=$FONT_SHA
EOF
grep -Fq "TARGET=$RG35XX_FONT_RUNTIME_PATH" "$RG35XX_ASSEMBLY_ROOT/rg35xx_runtime_files.list" || fail "runtime deployment target missing"
if grep -Fq "$RG35XX_RUNTIME_ASSEMBLY_ROOT" "$RG35XX_RUNTIME_ASSEMBLY_ROOT/gnu/java/awt/font/fonts.properties"; then
  fail "fonts.properties leaked disposable assembly path"
fi

COUNT=$(find "$RG35XX_ASSEMBLY_ROOT/src/libretro" -maxdepth 1 -name freej2me_libretro.c | wc -l | tr -d ' ')
[ "$COUNT" = 1 ] || fail "expected one freej2me_libretro.c, found $COUNT"
for f in media_cache media_event_queue audio_dispatch audio_pipe mixer midi_backend tsf_worker tsf_impl soundfont_source media_runtime; do
  [ -f "$RG35XX_ASSEMBLY_ROOT/src/libretro/rg35xx/rg35xx_${f}.c" ] || fail "missing native unit rg35xx_${f}.c"
done

note "RUNTIME/MAKE/FONT OVERLAY STRUCTURE PASS"
note "Font runtime mapping is deployment-safe: no disposable host path is embedded."
note "Deployment manifest: $RG35XX_ASSEMBLY_ROOT/rg35xx_runtime_files.list"
note "No BUILD-PASS: Classpath/JamVM compilation, glyph smoke probes and ARMv5TE/uClibc compile/link remain required."
