#!/bin/sh
set -eu

# RGJ-RC1-011K — GNU Classpath/runtime + native Make overlay gate.
# Operates only on disposable assembled trees.

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
: "${RG35XX_ASSEMBLY_ROOT:?set RG35XX_ASSEMBLY_ROOT to the 011J assembled FreeJ2ME tree}"
: "${RG35XX_CLASSPATH_ROOT:?set RG35XX_CLASSPATH_ROOT to GNU Classpath 0.99 source}"
: "${RG35XX_RUNTIME_ASSEMBLY_ROOT:?set RG35XX_RUNTIME_ASSEMBLY_ROOT to a disposable GNU Classpath output tree}"

fail() { echo "RC1 RUNTIME OVERLAY: FAIL: $*" >&2; exit 1; }
note() { echo "RC1 RUNTIME OVERLAY: $*"; }

[ -f "$RG35XX_ASSEMBLY_ROOT/src/libretro/freej2me_libretro.c" ] || fail "011J assembled FreeJ2ME tree missing"
[ -f "$RG35XX_ASSEMBLY_ROOT/src/libretro/rg35xx/rc1_sources.mk" ] || fail "011J native source manifest missing"
[ -f "$RG35XX_CLASSPATH_ROOT/gnu/java/awt/peer/headless/HeadlessToolkit.java" ] || fail "GNU Classpath 0.99 HeadlessToolkit missing"
[ "$RG35XX_RUNTIME_ASSEMBLY_ROOT" != "$RG35XX_CLASSPATH_ROOT" ] || fail "runtime assembly must not mutate Classpath source"

rm -rf "$RG35XX_RUNTIME_ASSEMBLY_ROOT"
mkdir -p "$RG35XX_RUNTIME_ASSEMBLY_ROOT"
( cd "$RG35XX_CLASSPATH_ROOT" && tar --exclude=.git -cf - . ) | ( cd "$RG35XX_RUNTIME_ASSEMBLY_ROOT" && tar -xf - )

# 0022 is intentionally an assembly contract, not a blindly applicable historical diff.
# Refuse to pretend it was applied until a concrete non-null FontPeer implementation exists.
PEER="$RG35XX_RUNTIME_ASSEMBLY_ROOT/gnu/java/awt/peer/headless/HeadlessToolkit.java"
grep -q 'getFontPeer' "$PEER" || fail "HeadlessToolkit has no getFontPeer entry point"
grep -q 'getClasspathFontPeer' "$PEER" || fail "HeadlessToolkit has no getClasspathFontPeer entry point"

# Generate, rather than overwrite, the Make integration fragment. The pinned upstream
# Makefile/Makefile.common remains authoritative for platform detection and output naming.
cat > "$RG35XX_ASSEMBLY_ROOT/src/libretro/rg35xx/rc1_make_overlay.mk" <<'EOF'
# Generated by RGJ-RC1-011K. Include from pinned src/libretro/Makefile.common.
include rg35xx/rc1_sources.mk
SOURCES_C += $(RG35XX_NATIVE_SRCS)
INCFLAGS += $(RG35XX_NATIVE_CFLAGS)
# Target toolchain must supply pthread/math equivalents. Do not infer host flags as target proof.
RG35XX_REQUIRED_LIBS := pthread m
EOF

# Structural native graph checks before any compiler is invoked.
COUNT=$(find "$RG35XX_ASSEMBLY_ROOT/src/libretro" -maxdepth 1 -name freej2me_libretro.c | wc -l | tr -d ' ')
[ "$COUNT" = 1 ] || fail "expected one freej2me_libretro.c, found $COUNT"
for f in media_cache media_event_queue audio_dispatch audio_pipe mixer midi_backend tsf_worker tsf_impl soundfont_source media_runtime; do
  [ -f "$RG35XX_ASSEMBLY_ROOT/src/libretro/rg35xx/rg35xx_${f}.c" ] || fail "missing native unit rg35xx_${f}.c"
done

note "RUNTIME/MAKE OVERLAY STRUCTURE PASS"
note "No BUILD-PASS: concrete Classpath FontPeer implementation, font resource installation and ARMv5TE/uClibc compile/link remain required."
